services:
  brat:
    restart: unless-stopped
    build: .
    container_name: 'brat-latest'
    ports:
    - 55557:8001
    volumes:
      - ./data:/brat/data
      - ./work:/brat/work
      - ./users.json:/brat/users.json
    environment:
      - 'COMMIT_SHA=44ecd825810167eed2a5d8ad875d832218e734e8'
